spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tms
    username: tms
    password: tms
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    locations: classpath:db/migration/postgres
