server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    # Die Location wird pro Profil überschrieben!
    locations: classpath:db/migration

jackson:
  serialization:
    write-dates-as-timestamps: false

security:
  jwt:
    secret: ${JWT_SECRET:ersetzen-durch-einen-langen-mindestens-32-zeichen-random-secret}
    ttlSeconds: 7200
