server:
  port: 8081

  # (Optional) GZIP/Br-Kompression für Antworten
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json, text/html, text/css, application/javascript

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/th_spedition?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: "Alim0710."
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

# 👉 CORS bitte in SecurityConfig lassen; daher KEIN spring.mvc.cors hier.
# spring:
#   mvc:
#     cors:
#       mappings: ...

security:
  jwt:
    secret: "ersetzen-durch-einen-langen-mindestens-32-zeichen-random-secret"
    ttlSeconds: 7200 # 2 Stunden
